spring.application.name=emergencia
spring.datasource.url=jdbc:postgresql://localhost:5432/emergencia_db    
spring.datasource.username=postgres
spring.datasource.password=1234

# Auto-crear y actualizar las tablas en la base de datos
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.enabled=true
logging.level.org.springframework.jdbc.datasource.init=DEBUG
